### ISSUE TITLE
Plan for the next Sprint on a wiki page

### ISSUE THREAD

**Issue by Mrizek** [CrazyComrades/crazy_comrades-soen341projectW2024#11]

**Comment by whoisyazzy** [comment]
URGENT : SPRINT 1 AND SPRINT 2 NEEDS TO BE DONE TAKE EXAMPLE AS PROVIDED BY THE TEACHER

**Comment by AndrewKeleny** [comment]
The planning for the next sprint is now done and it can be found under wiki.
