### ISSUE TITLE
Project approach and technology (Use template)

### ISSUE THREAD

**Issue by Mrizek** [CrazyComrades/crazy_comrades-soen341projectW2024#6]

**Comment by ElectricalEngineerStudent** [comment]
I added the point 5 and its content

**Comment by whoisyazzy** [comment]
Finished point 1, point 2 ; might need more info to complete the timeline in point 2 ; waiting for part 3,4 to complete part 6

**Comment by Mrizek** [comment]
Finished points 3 and 4. I suggest that the person who added point 5 reconsider some of the parts he wrote, since we will not be able to add all these security measures to our website.

**Comment by ElectricalEngineerStudent** [comment]
I have updated the point number 5

**Comment by whoisyazzy** [comment]
Finished the conclusion, closed the issue
